### ISSUE TITLE
describegpt: add tests

### ISSUE THREAD

**Issue by rzmk** [jqnatividad/qsv#1114]
## 🗺 Overview

Add tests to [qsv](https://github.com/jqnatividad/qsv)'s `describegpt` command.

## 📌 Tasks

- [x] Tests
  - [x] Use an invalid key and get the expected error response
  - [x] If setting the `--user-agent` option, get the expected user-agent in the header
  - [x] "valid" test with `#[ignore]` that fetches a successful response (set `QSV_OPENAI_KEY` in local env var)
    - "valid" tests show users examples of using the command and what to expect

**Comment by rzmk** [comment]
@jqnatividad For the invalid key I set a random value in `.env`. However, trying to get `stderr` output includes the status messages, so I'm wondering how I should set up an assertion.

https://github.com/jqnatividad/qsv/blob/3288f8060d0e719f71e0fc61db970227ff9d2b6f/src/cmd/describegpt.rs#L100

```console
test test_describegpt::invalid_api_key ... FAILED

failures:

---- test_describegpt::invalid_api_key stdout ----
thread 'test_describegpt::invalid_api_key' panicked at 'assertion failed: `(left == right)`
  left: `"Generating stats from in.csv using qsv stats --everything...\nGenerating frequency from in.csv using qsv frequency...\nInteracting with OpenAI API...\n\nGenerating tags from OpenAI API...\nOpenAI API Error: {\"message\":\"Incorrect API key provided: asdfasfadssf. You can find your API 
key at https://platform.openai.com/account/api-keys.\",\"type\":\"invalid_request_error\",\"param\":null,\"code\":\"invalid_api_key\"}\n"`,
 right: `""`', tests\test_describegpt.rs:25:5
 ```

**Comment by jqnatividad** [comment]
Hi @rzmk ,

You can do something like this:

```rust
    let mut cmd = wrk.command("describegpt");
    cmd.arg("--all").arg("--json").args(["--openai-key","INVALIDKEY"]).arg("in.csv");

    let output = cmd.output().unwrap();
    let got_stderr= std::str::from_utf8(&output.stderr).unwrap_or_default();

    assert!(
        got_stderr.contains("Incorrect API key provided: INVALIDKEY"));
    );
```
